### ISSUE TITLE
复现结果

### ISSUE THREAD

**Issue by wensongc** [ytZhang99/AHDRNet-PyTorch#1]
大佬您好，谢谢你的工作，请问一下这个代码能够复现论文中的结果吗？

**Comment by ytZhang99** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    应该是不太能，当时写完这个代码之后没什么时间好好调试训练，所以结果应该是比较差的，就只是单纯分享了一下思路QAQ，有时间可以尝试训练复现一下
    
        
            
        
    
    
     
    
        
                    Yutong ZhangPostgraduate Student of MC^2 ***@***.***
        
    
 

    在2022年4月21日 ***@***.***> 写道： 




大佬您好，谢谢你的工作，请问一下这个代码能够复现论文中的结果吗？

**Comment by wensongc** [comment]
好的，谢谢大佬
